name: CMake Build Matrix

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.18.4
  NINJA_VERSION: 1.10.1
  BUILD_TYPE: Release
  CCACHE_VERSION: 3.7.7
  NINJA_STATUS: "[%f/%t %o/sec] "

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows 2019 MSVC", artifact: "Windows-MSVC.7z",
            os: windows-2019,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            gpu_var: "Off",
            openmp_var: "Off"
          }
        - {
            name: "Windows 2022 MSVC", artifact: "Windows-MSVC-2022.7z",
            os: windows-2022,
            cc: "cl.exe", cxx: "cl.exe",
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            gpu_var: "Off",
            openmp_var: "On"
          }

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      CI_JOB_ID: ${{ github.sha }} # Tell CMake it's running in CI
      OPENMP_VAR: ${{ matrix.config.openmp_var }}
      GPU_VAR: ${{ matrix.config.gpu_var }}
      ENVIRONMENT_SCRIPT: ${{ matrix.config.environment_script }}

    steps:
    - uses: actions/checkout@v3

    - name: Download Ninja and CMake
      run: cmake -P .github/scripts/download-ninja-cmake.cmake

    - name: Download ccache
      id: ccache
      shell: cmake -P {0}
      run: |
        set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v$ENV{CCACHE_VERSION}/${{ runner.os }}.tar.xz")
        file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)

    - name: ccache cache files
      uses: actions/cache@v3
      with:
        path: .ccache
        key: ${{ matrix.config.name }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ matrix.config.name }}-ccache-

    - name: Configure
      run: cmake -P .github/scripts/configure.cmake

    - name: Build
      run: cmake -P .github/scripts/build.cmake

    - name: Run tests
      run: cmake -P .github/scripts/test.cmake


